### ISSUE TITLE
How is "Lich" pronounced?

### ISSUE THREAD

**Issue by codekiln** [ChadMcKinney/Lich.js#2]

**Comment by ChadMcKinney** [comment]
A lich is a zombie wizard and I've always heard it prounouned like a mix between lick and the end of sandwich. If you want to go deep there's a video that goes into the pronunciation and history of the word here:

https://www.youtube.com/watch?v=sIalyhyrCHw

**Comment by the-simian** [comment]
NB: I'm referencing this as the greatest github issue this week.

**Comment by codekiln** [comment]
I'll vote for that! Thanks @ChadMcKinney
